package com.omar.model.faction;

public class FactionNames {
    public static String[] factionNames = {
            "Crimson Reavers",
            "Shadow Syndicate",
            "Astral Knights",
            "Emberclaw Dominion",
            "Sable Serpents",
            "Azure Alliance",
            "Sylvan Enclave",
            "Ebon Legion",
            "Scarlet Brotherhood",
            "Golden Dominion",
            "Ironclad Warband",
            "Frostbite Clan",
            "Eclipse Empire",
            "Celestial Order",
            "Obsidian Covenant",
            "Luminous Vanguard",
            "Sapphire Court",
            "Verdant Pact",
            "Ravenwing Syndicate",
            "Stellar Conclave",
            "Crimson Lotus",
            "Onyx Collective",
            "Thunderclad Tribe",
            "Silvermist Union",
            "Vermillion Guild",
            "Tempest Enforcers",
            "Cobalt Council",
            "Starborn Collective",
            "Cindercliff Clan",
            "Harmony Assembly",
            "Shrouded Ascendancy",
            "Violet Dominion",
            "Sovereign Blades",
            "Crystalline Enigma",
            "Stormwatchers",
            "Crimson Claw",
            "Gilded Conquest",
            "Eclipse Syndicate",
            "Abyssal Conclave",
            "Veridian Pact",
            "Ironheart Crusade",
            "Moonshadow Clan",
            "Sunfire Coalition",
            "Ebonstar Covenant",
            "Sapphire Reach",
            "Copperclad Order",
            "Stardust Brotherhood",
            "Scarlet Serpent",
            "Cobalt Alliance",
            "Silent Nexus",
            "Emberstone Empire",
            "Astral Dominion",
            "Ravenclaw Guild",
            "Celestial Vanguard",
            "Silverleaf Enclave"
    };
}
